<?php
/**
 * Autogenerated Library by Irishmiss
 */
$miss_assets = Array(
    "jquery" => Array(
	"#hash" => "d223e1439188e478349d52476506c22e",
	"#active" => true,
	"#footer" => true,
	"#library" => Array( "jquery" ),
	"#scripts" => Array(
'packed.js',	),
    ),
    "fonts" => Array(
	"#hash" => "980d14c0c85495b48b9a9134658e6121",
	"#active" => true,
	"#footer" => false,
	"#styles" => Array(
'packed.css',	),
    ),
    "bootstrap" => Array(
	"#hash" => "ca4c50b905dc21ea17a10549a6f5944f",
	"#active" => true,
	"#footer" => true,
	"#reg" => true,
	"#library" => Array( "bootstrap" ),
	"#scripts" => Array(
'packed.js',	),
    ),
    "extensions" => Array(
	"#hash" => "2ac737d240fc746cef37129b7569f08e",
	"#active" => true,
	"#footer" => true,
	"#library" => Array( "jquery" ),
	"#scripts" => Array(
'packed.js',	),
	"#styles" => Array(
/*'packed.css',*/	),
    ),
    "generic" => Array(
	"#hash" => "3d517f8924ac7fd03699a29d97dc52d9",
	"#active" => true,
	"#footer" => true,
	"#library" => Array( "jquery" ),
	"#scripts" => Array(
'packed.js',	),
	"#styles" => Array(
/*'packed.css', 'template.css'*/	),
    ),
    "isotope" => Array(
	"#hash" => "a8b1c31fc8c4c565d63b478eddb9b172",
	"#active" => true,
	"#footer" => false,
	"#library" => Array( "jquery" ),
	"#scripts" => Array(
'packed.js',	),
    ),
    "init" => Array(
	"#hash" => "e37f0136aa3ffaf149b351f6a4c948e9",
	"#active" => true,
	"#footer" => true,
	"#library" => Array( "jquery" ),
	"#scripts" => Array(
'packed.js',	),
    ),
    "responsive" => Array(
	"#hash" => "3e80ebd582f73299f249afba8ebe7e6b",
	"#active" => true,
	"#footer" => true,
	"#styles" => Array(
/*'packed.css',*/	),
    ),
);
return $miss_assets;
?>